FROM cloudflare/cloudflared:2024.11.0-amd64

LABEL \
  io.hass.version="2024.11.0" \
  io.hass.type="addon" \
  io.hass.arch="amd64"

# Copy root filesystem
COPY rootfs /

# Set the working directory
WORKDIR /