name: Builder

env:
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    permissions:
      contents: read
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7.0.1

      - name: Get changed files
        id: changed_files
        if: github.event_name != 'workflow_dispatch'
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        env:
          ADDONS: ${{ steps.addons.outputs.addons }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual trigger: building all add-ons";
            addons=$(echo ${ADDONS} | sed 's/ /","/g')
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[\"${addons}\"]" >> $GITHUB_OUTPUT;
            exit 0
          fi

          declare -a changed_addons
          for addon in ${ADDONS}; do
            if [[ "${CHANGED_FILES}" =~ $addon ]]; then
              for file in ${MONITORED_FILES}; do
                  if [[ "${CHANGED_FILES}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)

          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi
  build:
    needs: init
    runs-on: ${{ matrix.os }}
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
        arch: ["aarch64", "amd64"]
        include:
          - arch: aarch64
            os: ubuntu-24.04-arm
          - arch: amd64
            os: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Check if add-on should be built
        id: check
        env:
          ADDON: ${{ matrix.addon }}
          ARCH: ${{ matrix.arch }}
          INFO_ARCHITECTURES: ${{ steps.info.outputs.architectures }}
          INFO_IMAGE: ${{ steps.info.outputs.image }}
          INFO_VERSION: ${{ steps.info.outputs.version }}
        run: |
          image=$(tr -d '"' <<< "${INFO_IMAGE}")

          if [[ "${image}" == "null" || -z "${image}" ]]; then
            echo "Image property is not defined, skipping build"
            echo "build_arch=false" >> "$GITHUB_OUTPUT"
          elif [[ "${INFO_ARCHITECTURES}" =~ ${ARCH} ]]; then
            echo "build_arch=true" >> "$GITHUB_OUTPUT"
            echo "image=${image//\{arch\}/${ARCH}}" >> "$GITHUB_OUTPUT"
            echo "version=$(tr -d '"' <<< "${INFO_VERSION}")" >> "$GITHUB_OUTPUT"
            echo "build_from=$(yq e -N -M ".build_from.\"${ARCH}\"" "./${ADDON}/build.yaml")" >> "$GITHUB_OUTPUT"
          else
            echo "${ARCH} is not a valid arch for ${ADDON}, skipping build"
            echo "build_arch=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          build-args: |
            BUILD_FROM=${{ steps.check.outputs.build_from }}
          cache-gha-scope: ${{ matrix.addon }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          context: "./${{ matrix.addon }}"
          image: ${{ steps.check.outputs.image }}
          image-tags: |
            ${{ steps.check.outputs.version }}
            latest
          push: ${{ github.event_name == 'push' }}
          version: ${{ steps.check.outputs.version }}

  build-status:
    name: Build status
    runs-on: ubuntu-latest
    needs: [init, build]
    if: always()
    steps:
      - name: Check build result
        run: |
          if [[ "${{ needs.build.result }}" == "failure" ]]; then
            exit 1
          fi
